<?php
namespace Doctrine\Search\Mapping\Annotations;


require_once '/Users/mikelohmann/Sites/doctrine-searc.local/search/lib/Doctrine/Search/Mapping/Annotations/DoctrineAnnotations.php';

/**
 * Test class for Searchable.
 * Generated by PHPUnit on 2011-12-13 at 08:34:52.
 */
class SearchableTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Searchable
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Searchable;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
